apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-management
  labels:
    app: author-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-management
  template:
    metadata:
      labels:
        app: author-management
    spec:
      containers:
        - name: author-management
          image: "ktaivleminiproject5.azurecr.io/author-management:latest"
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8082
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8082
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
