server:
  port: 8086

spring:
  application:
    name: manuscriptpublication
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: ManuscriptPublication
          destination: ktaivleminitocode
          contentType: application/json
        event-out:
          destination: ktaivleminitocode
          contentType: application/json

openai:
  api:
    url: ${OPENAI_API_URL:https://api.openai.com}
    key: ${OPENAI_API_KEY:sk-test-dummy-key-for-development-testing-only}

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: ManuscriptPublication
          destination: ktaivleminitocode
          contentType: application/json
        event-out:
          destination: ktaivleminitocode
          contentType: application/json

openai:
  api:
    url: ${OPENAI_API_URL:https://api.openai.com}
    key: ${OPENAI_API_KEY:sk-test-dummy-key-for-development-testing-only}
