apiVersion: apps/v1
kind: Deployment
metadata:
  name: manuscript-publication
  labels:
    app: manuscript-publication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manuscript-publication
  template:
    metadata:
      labels:
        app: manuscript-publication
    spec:
      containers:
        - name: manuscript-publication
          image: "ktaivleminiproject5.azurecr.io/manuscript-publication:latest"
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
                  optional: true
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
