apiVersion: v1
kind: Service
metadata:
  name: manuscript-publication
  labels:
    app: manuscript-publication
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: manuscript-publication
