apiVersion: v1
kind: Namespace
metadata:
  name: ktaivleminiproject5

---
# Kafka ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: ktaivleminiproject5
data:
  CLUSTER_ID: "kraft-cluster-01"
  KAFKA_KRAFT_MODE: "true"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_LOG_RETENTION_HOURS: "168"

---
# Kafka Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 9093
        envFrom:
        - configMapRef:
            name: kafka-config
        env:
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "kafka-topics --list --bootstrap-server localhost:9092"
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "kafka-topics --list --bootstrap-server localhost:9092"
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: kafka-storage
        emptyDir: {}

---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ktaivleminiproject5
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
  type: ClusterIP

---
# Author Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-management
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-management
  template:
    metadata:
      labels:
        app: author-management
    spec:
      containers:
      - name: author-management
        image: ktaivleminiproject5.azurecr.io/author-management:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30

---
# Author Management Service
apiVersion: v1
kind: Service
metadata:
  name: author-management
  namespace: ktaivleminiproject5
spec:
  selector:
    app: author-management
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP

---
# Subscription Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-management
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-management
  template:
    metadata:
      labels:
        app: subscription-management
    spec:
      containers:
      - name: subscription-management
        image: ktaivleminiproject5.azurecr.io/subscription-management:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30

---
# Subscription Management Service
apiVersion: v1
kind: Service
metadata:
  name: subscription-management
  namespace: ktaivleminiproject5
spec:
  selector:
    app: subscription-management
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
# Library Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
      - name: library-management
        image: ktaivleminiproject5.azurecr.io/library-management:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 30

---
# Library Management Service
apiVersion: v1
kind: Service
metadata:
  name: library-management
  namespace: ktaivleminiproject5
spec:
  selector:
    app: library-management
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP

---
# Point Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-management
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-management
  template:
    metadata:
      labels:
        app: point-management
    spec:
      containers:
      - name: point-management
        image: ktaivleminiproject5.azurecr.io/point-management:latest
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 30

---
# Point Management Service
apiVersion: v1
kind: Service
metadata:
  name: point-management
  namespace: ktaivleminiproject5
spec:
  selector:
    app: point-management
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP

---
# Manuscript Publication Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manuscript-publication
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manuscript-publication
  template:
    metadata:
      labels:
        app: manuscript-publication
    spec:
      containers:
      - name: manuscript-publication
        image: ktaivleminiproject5.azurecr.io/manuscript-publication:latest
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
              optional: true
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 60
          periodSeconds: 30

---
# Manuscript Publication Service
apiVersion: v1
kind: Service
metadata:
  name: manuscript-publication
  namespace: ktaivleminiproject5
spec:
  selector:
    app: manuscript-publication
  ports:
  - port: 8086
    targetPort: 8086
  type: ClusterIP

---
# Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ktaivleminiproject5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ktaivleminiproject5.azurecr.io/gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30

---
# Gateway Service (LoadBalancer for external access)
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ktaivleminiproject5
spec:
  selector:
    app: gateway
  ports:
  - port: 8088
    targetPort: 8080
  type: LoadBalancer

---
# OpenAI Secret (to be created separately)
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: ktaivleminiproject5
type: Opaque
data:
  api-key: c2stdGVzdC1kdW1teS1rZXktZm9yLWRldmVsb3BtZW50LXRlc3Rpbmctb25seQ== # base64 encoded dummy key
