apiVersion: v1
kind: Service
metadata:
  name: point-management
  labels:
    app: point-management
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: point-management
