apiVersion: v1
kind: Service
metadata:
  name: library-management
  labels:
    app: library-management
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: library-management
